# Generated by Django 6.0.5 on 2026-05-12 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('csv', 'CSV Format'), ('excel', 'Excel Format'), ('pdf', 'PDF Format')], max_length=10)),
                ('export_type', models.CharField(choices=[('all', 'All Profiles'), ('filtered', 'Filtered Profiles'), ('single', 'Single Profile')], default='all', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('record_count', models.IntegerField(default=0)),
                ('filters_used', models.JSONField(blank=True, default=dict, help_text='Filters applied during export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export History',
                'verbose_name_plural': 'Export Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
