# Generated by Django 6.0.5 on 2026-05-10 03:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_url', models.CharField(help_text='যেমন: http://user:pass@123.45.67.89:8080', max_length=255, unique=True, verbose_name='Proxy URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('success_count', models.IntegerField(default=0, verbose_name='Success Count')),
                ('fail_count', models.IntegerField(default=0, verbose_name='Fail Count')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('response_time', models.FloatField(default=0.0, help_text='Average response time in seconds', verbose_name='Response Time')),
            ],
            options={
                'verbose_name': 'Proxy Pool',
                'verbose_name_plural': 'Proxy Pool',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='LinkedIn প্রোফাইলের পুরো নাম', max_length=255, verbose_name='Full Name')),
                ('headline', models.CharField(blank=True, help_text="যেমন: 'Senior Software Engineer at Google'", max_length=500, null=True, verbose_name='Professional Headline')),
                ('location', models.CharField(blank=True, help_text='প্রোফাইলের লোকেশন (দেশ/শহর)', max_length=255, null=True, verbose_name='Location')),
                ('about', models.TextField(blank=True, help_text="LinkedIn প্রোফাইলের 'About' সেকশন", null=True, verbose_name='About Section')),
                ('skills', models.TextField(blank=True, help_text='স্কিলগুলো কমা দিয়ে আলাদা করা থাকবে', null=True, verbose_name='Skills')),
                ('experience', models.TextField(blank=True, help_text='কাজের অভিজ্ঞতার বিবরণ', null=True, verbose_name='Work Experience')),
                ('education', models.TextField(blank=True, help_text='শিক্ষাগত যোগ্যতা', null=True, verbose_name='Education')),
                ('linkedin_url', models.URLField(max_length=500, unique=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn Profile URL')),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Picture URL')),
                ('category', models.CharField(choices=[('recruiter', 'Recruiter'), ('hr', 'HR Professional'), ('backend_dev', 'Backend Developer'), ('frontend_dev', 'Frontend Developer'), ('fullstack_dev', 'Full Stack Developer'), ('devops', 'DevOps Engineer'), ('data_scientist', 'Data Scientist'), ('manager', 'Manager'), ('ceo', 'CEO/Founder'), ('marketing', 'Marketing Professional'), ('sales', 'Sales Professional'), ('other', 'Other')], db_index=True, default='other', max_length=50, verbose_name='AI Classified Category')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI ক্লাসিফিকেশনের confidence score (0-1)', verbose_name='AI Confidence Score')),
                ('search_keyword', models.CharField(blank=True, db_index=True, help_text='কোন keyword দিয়ে প্রোফাইলটি পাওয়া গেছে', max_length=255, null=True, verbose_name='Search Keyword Used')),
                ('is_scraped', models.BooleanField(default=False, help_text='সম্পূর্ণ প্রোফাইলের তথ্য নেয়া হয়েছে কিনা', verbose_name='Fully Scraped')),
                ('scrape_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked by LinkedIn')], default='pending', max_length=20, verbose_name='Scraping Status')),
                ('error_message', models.TextField(blank=True, help_text='স্ক্র্যাপিং-এ error হলে এখানে সংরক্ষণ হবে', null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Scraped At')),
            ],
            options={
                'verbose_name': 'LinkedIn Profile',
                'verbose_name_plural': 'LinkedIn Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='scraper_pro_categor_d85692_idx'), models.Index(fields=['search_keyword'], name='scraper_pro_search__eec4fd_idx'), models.Index(fields=['location'], name='scraper_pro_locatio_242236_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, verbose_name='Search Keyword')),
                ('total_results_found', models.IntegerField(default=0, verbose_name='Total Results Found')),
                ('profiles_scraped', models.IntegerField(default=0, verbose_name='Profiles Scraped')),
                ('search_duration', models.FloatField(default=0.0, help_text='সার্চ করতে কত সেকেন্ড লেগেছে', verbose_name='Search Duration (seconds)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Searched At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
