# Generated by Django 6.0.5 on 2026-05-10 04:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxypool',
            options={'ordering': ['-success_count'], 'verbose_name': 'Proxy Pool', 'verbose_name_plural': 'Proxy Pool'},
        ),
        migrations.AddField(
            model_name='proxypool',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='proxypool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxypool',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='Is Anonymous'),
        ),
        migrations.AddField(
            model_name='proxypool',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Checked'),
        ),
        migrations.AddField(
            model_name='proxypool',
            name='proxy_type',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks4', 'SOCKS4'), ('socks5', 'SOCKS5')], default='http', max_length=10, verbose_name='Proxy Type'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='profiles_saved',
            field=models.IntegerField(default=0, verbose_name='New Profiles Saved'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_scraped',
            field=models.BooleanField(default=False, verbose_name='Fully Scraped'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(max_length=500, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='search_keyword',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Search Keyword Used'),
        ),
        migrations.AlterField(
            model_name='proxypool',
            name='proxy_url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Proxy URL'),
        ),
        migrations.AlterField(
            model_name='proxypool',
            name='response_time',
            field=models.FloatField(default=0.0, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_duration',
            field=models.FloatField(default=0.0, verbose_name='Search Duration (seconds)'),
        ),
        migrations.AddIndex(
            model_name='proxypool',
            index=models.Index(fields=['is_active', 'success_count'], name='scraper_pro_is_acti_4a388b_idx'),
        ),
        migrations.AddIndex(
            model_name='proxypool',
            index=models.Index(fields=['country'], name='scraper_pro_country_525ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['keyword', 'created_at'], name='scraper_sea_keyword_8b0c75_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'created_at'], name='scraper_sea_user_id_ff0051_idx'),
        ),
    ]
